---
# SPDX-FileCopyrightText: 2025-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for pre-commit
#
# See: https://pre-commit.com

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.3.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/fsfe/reuse-tool
    rev: "v6.2.0"
    hooks:
      - id: reuse
        stages: [pre-commit]
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: "v3.6.2"
    hooks:
      - id: prettier
        stages: [pre-commit]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.18.1"
    hooks:
      - id: markdownlint-cli2
        stages: [pre-commit]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.37.1"
    hooks:
      - id: yamllint
        stages: [pre-commit]
        args: [--strict]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.34.1"
    hooks:
      - id: check-github-workflows
        stages: [pre-commit]
      - id: check-taskfile
        stages: [pre-commit]
